name: Terraform CI CD Pipeline for Deploying Infrastructure
run-name: ${{ github.actor }} has triggered the pipeline

on:
    push:
        branches:
            - main

env: 
    AWS_REGION: us-east-1
    GITHUB_REPO_URL: https://github.com/myingineer/habit_tracker

jobs:
    deploy-and-test:
        name: Deploy Infrastructure and Test then Destroy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.10.5

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Terraform Init
              run: terraform init
              working-directory: ./

            - name: Terraform Apply
              run: terraform apply -auto-approve
              env:
                TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} # Pass the DB password secret
                TF_VAR_vpc_cidr: "10.0.0.0/16"  # Pass the VPC CIDR
                TF_VAR_public_subnet_cidrs: '["10.0.1.0/24", "10.0.2.0/24"]'  # Pass the public subnet CIDRs
                TF_VAR_private_subnet_cidrs: '["10.0.3.0/24", "10.0.4.0/24"]'  # Pass the private subnet CIDRs
              working-directory: ./

            - name: Wait for API to be Ready
              run: sleep 900s

            - name: Extract ALB DNS Name
              working-directory: ./
              run: echo "ALB_URL=$(terraform output -raw alb_dns_name)" >> $GITHUB_ENV

            - name: Deploy Habit Tracker on EC2 (via AWS SSM)
              run: |
                aws ssm send-command \
                  --region $AWS_REGION \
                  --document-name "AWS-RunShellScript" \
                  --targets "Key=tag:Name,Values=habit-tracker-ec2" \
                  --parameters 'commands=[
                    "sudo apt update -y",
                    "sudo apt install -y python3-pip git",
                    "git clone $GITHUB_REPO_URL /home/ubuntu/habit-tracker || (cd /home/ubuntu/habit-tracker && git pull)",
                    "cd /home/ubuntu/habit-tracker",
                    "echo DB_URL=${{ secrets.DB_URL }} >> .env",  # Create .env file with DB_URL
                    "echo DB_PORT=${{ secrets.DB_PORT }} >> .env",  # Create .env file with DB_PORT
                    "echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env",  # Create .env file with DB_PASSWORD
                    "echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env",  # Create .env file with DB_USERNAME
                    "echo DB_NAME=${{ secrets.DB_NAME }} >> .env",  # Create .env file with DB_NAME
                    "echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env",  # Create .env file with SECRET_KEY
                    "echo ALGORITHM=${{ secrets.ALGORITHM }} >> .env",  # Create .env file with ALGORITHM
                    "echo ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }} >> .env",  # Create .env file with ACCESS_TOKEN_EXPIRE_MINUTES
                    "echo EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} >> .env",  # Create .env file with EMAIL_ADDRESS
                    "echo EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }} >> .env",  # Create .env file with EMAIL_APP_PASSWORD
                    "pip3 install -r requirements.txt",
                    "nohup python3 main.py > app.log 2>&1 &"
                  ]' \
                  --comment "Deploy habit tracker backend"

            - name: Wait for API to be Ready
              run: sleep 120

            - name: Setup Python for Testing
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install Testing Dependencies
              run: pip install pytest httpx

            - name: Run API Tests
              run: pytest tests/ --base-url=https://${{ env.ALB_URL }}

            - name: Terraform Output
              run: terraform output
              working-directory: ./

            - name: Terraform Destroy
              run: terraform destroy -auto-approve
              working-directory: ./